services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5431:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

# pgdatabase and pgadmin are names (set arbitrarily) for the 2 containers we are creating
# images: specify which image to use within the specific container it is under
# environment: used to specify environmental variables
# volume: set up volume using relative path, rw = rewrite mode. rmb to use ""
# ports: ports to use i.e. local:container

# fin
